# exceptions.py
class NoteNotFoundException(Exception):
    """Исключение, возникающее, когда заметка не найдена."""
    pass